services:
  - type: web
    name: nexus-backtester
    runtime: python        # “env: python” → “runtime:” in new spec
    buildCommand: |
      pip install -r requirements.txt
    preDeployCommand: |
      FLASK_APP=app.py flask db upgrade
    startCommand: |
      gunicorn app:app --timeout 300 --bind 0.0.0.0:$PORT --workers 2
    disk:                  # ← add this block
      name: data           # arbitrary label
      mountPath: /data     # absolute, non-root path
      sizeGB: 1            # first 1 GB is free on Render

    envVars:
      - key: DATA_DIR      # optional; lets app find the disk path
        value: /data
      - key: SECRET_KEY
        generateValue: true
