"""initial schema

Revision ID: 739a6f41ee34
Revises:
Create Date: 2025-06-25 18:27:30.216101

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "739a6f41ee34"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("pw_hash", sa.String(length=255), nullable=False),
        sa.Column("stripe_cus", sa.String(length=120), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
