"""Initial migration

Revision ID: a03fd3c3da53
Revises: 
Create Date: 2025-06-25 05:31:18.287062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03fd3c3da53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pw_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('stripe_cus', sa.String(length=120), nullable=True))
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('stripe_cus')
        batch_op.drop_column('pw_hash')

    # ### end Alembic commands ###
