"""Add leaderboard columns to User model

Revision ID: de97489c4113
Revises: 739a6f41ee34
Create Date: 2025-08-25 14:11:29.119261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de97489c4113'
down_revision = '739a6f41ee34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_net_pl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_backtests', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_backtests')
        batch_op.drop_column('total_net_pl')

    # ### end Alembic commands ###
